/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppValidationRouteImport } from './routes/app.validation'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppMeasureRouteImport } from './routes/app.measure'
import { Route as AppHierarchieRouteImport } from './routes/app.hierarchie'
import { Route as AppDebugRouteImport } from './routes/app.debug'
import { Route as AppChangePasswordRouteImport } from './routes/app.change-password'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppParcellesIndexRouteImport } from './routes/app.parcelles.index'
import { Route as AppParcellesNewRouteImport } from './routes/app.parcelles.new'
import { Route as AppParcellesIdRouteImport } from './routes/app.parcelles.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppValidationRoute = AppValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppMeasureRoute = AppMeasureRouteImport.update({
  id: '/measure',
  path: '/measure',
  getParentRoute: () => AppRoute,
} as any)
const AppHierarchieRoute = AppHierarchieRouteImport.update({
  id: '/hierarchie',
  path: '/hierarchie',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugRoute = AppDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AppRoute,
} as any)
const AppChangePasswordRoute = AppChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppParcellesIndexRoute = AppParcellesIndexRouteImport.update({
  id: '/parcelles/',
  path: '/parcelles/',
  getParentRoute: () => AppRoute,
} as any)
const AppParcellesNewRoute = AppParcellesNewRouteImport.update({
  id: '/parcelles/new',
  path: '/parcelles/new',
  getParentRoute: () => AppRoute,
} as any)
const AppParcellesIdRoute = AppParcellesIdRouteImport.update({
  id: '/parcelles/$id',
  path: '/parcelles/$id',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/app/debug': typeof AppDebugRoute
  '/app/hierarchie': typeof AppHierarchieRoute
  '/app/measure': typeof AppMeasureRoute
  '/app/users': typeof AppUsersRoute
  '/app/validation': typeof AppValidationRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/parcelles/$id': typeof AppParcellesIdRoute
  '/app/parcelles/new': typeof AppParcellesNewRoute
  '/app/parcelles/': typeof AppParcellesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/app/debug': typeof AppDebugRoute
  '/app/hierarchie': typeof AppHierarchieRoute
  '/app/measure': typeof AppMeasureRoute
  '/app/users': typeof AppUsersRoute
  '/app/validation': typeof AppValidationRoute
  '/app': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/parcelles/$id': typeof AppParcellesIdRoute
  '/app/parcelles/new': typeof AppParcellesNewRoute
  '/app/parcelles': typeof AppParcellesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/app/debug': typeof AppDebugRoute
  '/app/hierarchie': typeof AppHierarchieRoute
  '/app/measure': typeof AppMeasureRoute
  '/app/users': typeof AppUsersRoute
  '/app/validation': typeof AppValidationRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/parcelles/$id': typeof AppParcellesIdRoute
  '/app/parcelles/new': typeof AppParcellesNewRoute
  '/app/parcelles/': typeof AppParcellesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/change-password'
    | '/app/debug'
    | '/app/hierarchie'
    | '/app/measure'
    | '/app/users'
    | '/app/validation'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/parcelles/$id'
    | '/app/parcelles/new'
    | '/app/parcelles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/change-password'
    | '/app/debug'
    | '/app/hierarchie'
    | '/app/measure'
    | '/app/users'
    | '/app/validation'
    | '/app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/parcelles/$id'
    | '/app/parcelles/new'
    | '/app/parcelles'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/change-password'
    | '/app/debug'
    | '/app/hierarchie'
    | '/app/measure'
    | '/app/users'
    | '/app/validation'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/parcelles/$id'
    | '/app/parcelles/new'
    | '/app/parcelles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/validation': {
      id: '/app/validation'
      path: '/validation'
      fullPath: '/app/validation'
      preLoaderRoute: typeof AppValidationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/measure': {
      id: '/app/measure'
      path: '/measure'
      fullPath: '/app/measure'
      preLoaderRoute: typeof AppMeasureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hierarchie': {
      id: '/app/hierarchie'
      path: '/hierarchie'
      fullPath: '/app/hierarchie'
      preLoaderRoute: typeof AppHierarchieRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debug': {
      id: '/app/debug'
      path: '/debug'
      fullPath: '/app/debug'
      preLoaderRoute: typeof AppDebugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/change-password': {
      id: '/app/change-password'
      path: '/change-password'
      fullPath: '/app/change-password'
      preLoaderRoute: typeof AppChangePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/parcelles/': {
      id: '/app/parcelles/'
      path: '/parcelles'
      fullPath: '/app/parcelles/'
      preLoaderRoute: typeof AppParcellesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parcelles/new': {
      id: '/app/parcelles/new'
      path: '/parcelles/new'
      fullPath: '/app/parcelles/new'
      preLoaderRoute: typeof AppParcellesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parcelles/$id': {
      id: '/app/parcelles/$id'
      path: '/parcelles/$id'
      fullPath: '/app/parcelles/$id'
      preLoaderRoute: typeof AppParcellesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppChangePasswordRoute: typeof AppChangePasswordRoute
  AppDebugRoute: typeof AppDebugRoute
  AppHierarchieRoute: typeof AppHierarchieRoute
  AppMeasureRoute: typeof AppMeasureRoute
  AppUsersRoute: typeof AppUsersRoute
  AppValidationRoute: typeof AppValidationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppParcellesIdRoute: typeof AppParcellesIdRoute
  AppParcellesNewRoute: typeof AppParcellesNewRoute
  AppParcellesIndexRoute: typeof AppParcellesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChangePasswordRoute: AppChangePasswordRoute,
  AppDebugRoute: AppDebugRoute,
  AppHierarchieRoute: AppHierarchieRoute,
  AppMeasureRoute: AppMeasureRoute,
  AppUsersRoute: AppUsersRoute,
  AppValidationRoute: AppValidationRoute,
  AppIndexRoute: AppIndexRoute,
  AppParcellesIdRoute: AppParcellesIdRoute,
  AppParcellesNewRoute: AppParcellesNewRoute,
  AppParcellesIndexRoute: AppParcellesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
