// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ckkjqpsoavrikgiuuktf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNra2pxcHNvYXZyaWtnaXV1a3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1NDY1MDYsImV4cCI6MjEwMjEyMjUwNn0.XJREMPDEOyswhr7bLGE0TwKaRQyCWmcAiyPBitAPOOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Note: generated `Database` types are currently empty for this external project,
// so the client is loosely typed to keep app queries compiling.
export const supabase: SupabaseClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});