// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eejknddjlalccguseqbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlamtuZGRqbGFsY2NndXNlcWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4NTA3ODIsImV4cCI6MjA5NDQyNjc4Mn0.FXXXrZP6GM5yhv7KLMy0EsmeKL9C1qpR7-aCz67YzCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});